name: My Blog
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs: 
  blog:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      - name: Update README with latest YouTube videos
        uses: gautamkrishnar/blog-post-workflow@master
        with: 
          comment_tag_name: "SKIT-BLOG"
          feed_list: "https://www.sageknowsit.com/feed/"
          
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Updated with the latest Blog Post"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
