name: Youtube Video
on:
  schedule: # Use lowercase here
    - cron: '0 * * * *'
  workflow_dispatch: # Make sure this is properly aligned and does not have a colon after 'dispatch'

jobs: 
  youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with: 
          comment_tag_name: "YOUTUBE-VIDEOS-LIST"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCJ2qC60hPm0lIyhuj9ay04A"
